/**
 * This script generates TypeScript types based on the styles.json configuration
 * Run it with "npm run generate-types" or "yarn generate-types"
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { Gender } from '../lib/types'

// Get the directory name in ESM
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Define paths relative to project root
const configPath = path.resolve(__dirname, '../lib/config/styles.json');
const optionsPath = path.resolve(__dirname, '../lib/config/options.json');
const outputPath = path.resolve(__dirname, '../lib/generated-types.ts');

// Define types for the configuration
interface StyleConfig {
  id: string;
  name: string;
  description: string;
  previewImages: string[];
  availableBackgrounds: string[];
  availableOutfits: string[];
  availableOutfitColors: string[];
  availableGenders: Gender[];
}

interface BackgroundOption {
  id: string;
  label: string;
  imageUrl: string;
}

interface OutfitOption {
  id: string;
  label: string;
  imageUrl: string;
}

interface OptionsConfig {
  backgrounds: BackgroundOption[];
  outfits: OutfitOption[];
  outfitColors: { id: string; label: string }[];
}

// Read the configuration files
let stylesConfig: StyleConfig[];
let optionsConfig: OptionsConfig;

try {
  const stylesConfigRaw = fs.readFileSync(configPath, 'utf8');
  const optionsConfigRaw = fs.readFileSync(optionsPath, 'utf8');

  stylesConfig = JSON.parse(stylesConfigRaw) as StyleConfig[];
  optionsConfig = JSON.parse(optionsConfigRaw) as OptionsConfig;
} catch (error) {
  if (error instanceof Error) {
    if ('code' in error && error.code === 'ENOENT') {
      console.error('Error: Configuration file not found. Please ensure both files exist:');
      console.error(`- ${configPath}`);
      console.error(`- ${optionsPath}`);
    } else {
      console.error('Error reading or parsing configuration files:', error.message);
    }
  } else {
    console.error('An unexpected error occurred:', error);
  }
  process.exit(1);
}

// Extract unique IDs from the configuration
const styleIds = [...new Set(stylesConfig.map((style: StyleConfig) => style.id))];
const backgroundIds = [...new Set(optionsConfig.backgrounds.map((bg: BackgroundOption) => bg.id))];
const outfitIds = [...new Set(optionsConfig.outfits.map((outfit: OutfitOption) => outfit.id))];

// Generate the TypeScript code
const generateTypeScript = () => {
  // Create union types from the unique IDs
  const generateUnionType = (name: string, values: string[]) => {
    const unionValues = values.map((value: string) => `  | '${value}'`).join('\n');
    return `export type ${name} = \n${unionValues}`;
  };

  const styleType = generateUnionType('StylePhotographyStyle', styleIds);
  const backgroundType = generateUnionType('StyleBackground', backgroundIds);
  const outfitType = generateUnionType('StyleOutfit', outfitIds);

  // Create the full TypeScript file content
  return `// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT EDIT MANUALLY
// Source: scripts/generate-types.ts
// Generated from: lib/config/styles.json and lib/config/options.json

// Re-generate by running: npm run generate-types

${styleType}

${backgroundType}

${outfitType}

// Common types - manually maintained
export type StyleStatus = 'draft' | 'pending' | 'processing' | 'completed'

// Colors are strings (hex values, etc.)
export type StyleOutfitColor = string

// Gender type for user profiles and style settings
export type Gender = 'male' | 'female'

export type StyleSettings = {
  photographyStyle: StylePhotographyStyle
  outfit: StyleOutfit
  background: StyleBackground
  outfitColor?: StyleOutfitColor
  gender?: Gender
  customSettings?: Record<string, any>
}

// Generated on: ${new Date().toISOString()}
`;
};

// Generate the validation configuration
const generateValidationConfig = () => {
  return `// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT EDIT MANUALLY
// Source: scripts/generate-types.ts
// Generated from: lib/config/styles.json and lib/config/options.json

// Re-generate by running: npm run generate-types

import { StylePhotographyStyle, StyleBackground, StyleOutfit } from './generated-types';

export const validStyleIds: StylePhotographyStyle[] = ${JSON.stringify(styleIds, null, 2)} as const;

export const validBackgrounds: StyleBackground[] = ${JSON.stringify(backgroundIds, null, 2)} as const;

export const validOutfits: StyleOutfit[] = ${JSON.stringify(outfitIds, null, 2)} as const;

// Generated on: ${new Date().toISOString()}
`;
};

// Write the generated files
const typeScriptCode = generateTypeScript();
const validationCode = generateValidationConfig();
const validationOutputPath = path.resolve(__dirname, '../lib/generated-validation.ts');

try {
  // Ensure the output directory exists
  const outputDir = path.dirname(outputPath);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }
  
  // Write both files
  fs.writeFileSync(outputPath, typeScriptCode);
  fs.writeFileSync(validationOutputPath, validationCode);
  
  console.log(`Types successfully generated to ${outputPath}`);
  console.log(`Validation config generated to ${validationOutputPath}`);
  console.log(`✅ Found ${styleIds.length} styles, ${backgroundIds.length} backgrounds, and ${outfitIds.length} outfits`);
} catch (error) {
  if (error instanceof Error) {
    if ('code' in error && error.code === 'EACCES') {
      console.error('Error: Permission denied when writing generated files.');
      console.error(`Please check permissions for:`);
      console.error(`- ${outputPath}`);
      console.error(`- ${validationOutputPath}`);
    } else {
      console.error('Error writing generated files:', error.message);
    }
  } else {
    console.error('An unexpected error occurred while writing the files:', error);
  }
  process.exit(1);
} 