/**
 * This script generates TypeScript types based on the styles.json configuration
 * Run it with "npm run generate-types" or "yarn generate-types"
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

// Get the directory name in ESM
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Define paths relative to project root
const configPath = path.resolve(__dirname, '../lib/config/styles.json');
const optionsPath = path.resolve(__dirname, '../lib/config/options.json');
const outputPath = path.resolve(__dirname, '../lib/generated-types.ts');

// Define types for the configuration
interface StyleConfig {
  id: string;
  name: string;
  description: string;
  previewImages: string[];
  availableBackgrounds: string[];
  availableOutfits: string[];
  availableOutfitColors: string[];
}

interface BackgroundOption {
  id: string;
  label: string;
  imageUrl: string;
}

interface OutfitOption {
  id: string;
  label: string;
  imageUrl: string;
}

interface OptionsConfig {
  backgrounds: BackgroundOption[];
  outfits: OutfitOption[];
  outfitColors: { id: string; label: string }[];
}

// Read the configuration files
const stylesConfigRaw = fs.readFileSync(configPath, 'utf8');
const optionsConfigRaw = fs.readFileSync(optionsPath, 'utf8');

const stylesConfig = JSON.parse(stylesConfigRaw) as StyleConfig[];
const optionsConfig = JSON.parse(optionsConfigRaw) as OptionsConfig;

// Extract unique IDs from the configuration
const styleIds = [...new Set(stylesConfig.map((style: StyleConfig) => style.id))];
const backgroundIds = [...new Set(optionsConfig.backgrounds.map((bg: BackgroundOption) => bg.id))];
const outfitIds = [...new Set(optionsConfig.outfits.map((outfit: OutfitOption) => outfit.id))];

// Generate the TypeScript code
const generateTypeScript = () => {
  // Create union types from the unique IDs
  const generateUnionType = (name: string, values: string[]) => {
    const unionValues = values.map((value: string) => `  | '${value}'`).join('\n');
    return `export type ${name} = \n${unionValues}`;
  };

  const styleType = generateUnionType('StylePhotographyStyle', styleIds);
  const backgroundType = generateUnionType('StyleBackground', backgroundIds);
  const outfitType = generateUnionType('StyleOutfit', outfitIds);

  // Create the full TypeScript file content
  return `// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT EDIT MANUALLY
// Source: scripts/generate-types.ts
// Generated from: lib/config/styles.json and lib/config/options.json

// Re-generate by running: npm run generate-types

${styleType}

${backgroundType}

${outfitType}

// Common types - manually maintained
export type StyleStatus = 'draft' | 'pending' | 'processing' | 'completed'

// Colors are strings (hex values, etc.)
export type StyleOutfitColor = string

export type StyleSettings = {
  photographyStyle: StylePhotographyStyle
  outfit: StyleOutfit
  background: StyleBackground
  outfitColor?: StyleOutfitColor
  customSettings?: Record<string, any>
}

// Generated on: ${new Date().toISOString()}
`;
};

// Write the generated TypeScript to file
const typeScriptCode = generateTypeScript();
fs.writeFileSync(outputPath, typeScriptCode);

console.log(`Types successfully generated to ${outputPath}`);
console.log(`✅ Found ${styleIds.length} styles, ${backgroundIds.length} backgrounds, and ${outfitIds.length} outfits`); 