/**
 * SUPABASE EDGE FUNCTIONS PRICING CONSTANTS
 * 
 * ⚠️  AUTO-GENERATED - DO NOT EDIT MANUALLY!
 * This file is generated by scripts/sync-pricing.ts
 * To update pricing, edit common/lib/pricing-config.ts and run: npm run sync-pricing
 * 
 * Environment Variables (configurable in Supabase dashboard):
 * - CREDIT_COST_1K: Cost for 1K image generation (default: 1)
 * - CREDIT_COST_2K: Cost for 2K image generation (default: 2)
 * - CREDIT_COST_4K: Cost for 4K image generation (default: 3)
 * - CREDIT_COST_FACE_MODEL_TRAINING: Cost for Face Model training (default: 30)
 */

export type Resolution = '1K' | '2K' | '4K';

export interface CreditCosts {
  IMAGE_GENERATION: {
    [K in Resolution]: number;
  };
  FACE_MODEL_TRAINING: number;
}

export interface SubscriptionTier {
  id: string;
  name: string;
  displayName: string;
  description: string;
  monthlyPrice: number;
  yearlyPrice: number;
  credits: number;
  maxResolution: Resolution;
  faceModelTrainingIncluded: number;
  concurrentJobs: number;
  maxLoras: number;
  features: string[];
  popular?: boolean;
}

export interface CreditPack {
  id: string;
  name: string;
  credits: number;
  price: number;
  validityDays: number;
  costPerCredit: number;
  savings?: string;
}

/**
 * CONFIGURABLE CREDIT COSTS - reads from environment variables!
 * This is the main benefit - change pricing without code deployment
 */
export const CREDIT_COSTS: CreditCosts = {
  IMAGE_GENERATION: {
    '1K': parseInt(Deno.env.get('CREDIT_COST_1K') || '1'),
    '2K': parseInt(Deno.env.get('CREDIT_COST_2K') || '2'),
    '4K': parseInt(Deno.env.get('CREDIT_COST_4K') || '3')
  },
  FACE_MODEL_TRAINING: parseInt(Deno.env.get('CREDIT_COST_FACE_MODEL_TRAINING') || '30')
};

/**
 * Subscription tiers configuration
 * ⚠️  AUTO-GENERATED from common/lib/pricing-config.ts
 */
const SUBSCRIPTION_TIERS_CONFIG = [
  {
    id: 'tier_1',
    name: 'Basic',
    displayName: 'Basic',
    description: 'Includes 40 credits per month, plus 1 Face Model training (30 credits value).',
    originalPrice: 14,
    monthlyPrice: 9, // Discounted price
    yearlyPrice: 9, // Discounted yearly price (per month)
    credits: 40,
    maxResolution: '1K',
    faceModelTrainingIncluded: 1,
    concurrentJobs: 1,
    maxFaceModels: 1,
    features: [
      '40 monthly credits',
      'Standard image resolution (1K max)',
      'Includes 1 Face Model training',
      '1 concurrent job',
      '1 Face Model slot',
      'Up to 40 images per month'
    ],
    popular: false
  },
  {
    id: 'tier_2',
    name: 'Standard',
    displayName: 'Standard',
    description: 'Includes 180 credits per month, plus 1 Face Model training (30 credits value).',
    originalPrice: 39,
    monthlyPrice: 29, // Discounted price
    yearlyPrice: 18, // Discounted yearly price (per month)
    credits: 180,
    maxResolution: '4K',
    faceModelTrainingIncluded: 1,
    concurrentJobs: 2,
    maxFaceModels: 3,
    features: [
      '180 monthly credits',
      'Ultra high image resolution (up to 4K)',
      'Includes 1 Face Model training',
      '2 concurrent jobs',
      '3 Face Model slots',
      'Up to 180×1K, 90×2K, or 60×4K images per month'
    ],
    popular: true
  },
  {
    id: 'tier_3',
    name: 'Pro',
    displayName: 'Pro',
    description: 'Includes 450 credits per month, plus 3 Face Model trainings (90 credits value).',
    originalPrice: 89,
    monthlyPrice: 69, // Discounted price
    yearlyPrice: 39, // Discounted yearly price (per month)
    credits: 450,
    maxResolution: '4K',
    faceModelTrainingIncluded: 3,
    concurrentJobs: 4,
    maxFaceModels: 8,
    features: [
      '450 monthly credits',
      'Ultra high image resolution (up to 4K)',
      'Includes 3 Face Model trainings',
      '4 concurrent jobs',
      '8 Face Model slots',
      'Up to 450×1K, 225×2K, or 150×4K images per month'
    ],
    popular: false
  }
];

// Convert config format to match our SubscriptionTier interface
export const SUBSCRIPTION_TIERS: SubscriptionTier[] = SUBSCRIPTION_TIERS_CONFIG.map(tier => ({
  ...tier,
  // Convert monthly yearly price to annual price for consistency
  yearlyPrice: tier.yearlyPrice * 12
}));

/**
 * Credit packs configuration
 * ⚠️  AUTO-GENERATED from common/lib/pricing-config.ts
 */
export const CREDIT_PACKS: CreditPack[] = [
  {
    id: 'credits_90',
    name: '90 Credits',
    credits: 90,
    price: 19,
    validityDays: 60,
    costPerCredit: 0.211
  },
  {
    id: 'credits_180',
    name: '180 Credits',
    credits: 180,
    price: 32,
    validityDays: 60,
    costPerCredit: 0.177,
    savings: 'Save 16%'
  },
  {
    id: 'credits_360',
    name: '360 Credits',
    credits: 360,
    price: 58,
    validityDays: 60,
    costPerCredit: 0.16,
    savings: 'Save 24%'
  }
];

/**
 * Calculate credit cost for image generation
 */
export function calculateImageCreditCost(resolution: Resolution = '1K', batchSize: number = 1): number {
  return CREDIT_COSTS.IMAGE_GENERATION[resolution] * batchSize;
}

/**
 * Get credit cost for Face Model training
 */
export function getFaceModelTrainingCost(): number {
  return CREDIT_COSTS.FACE_MODEL_TRAINING;
}

/**
 * Calculate total credit cost for any operation
 */
export function calculateCreditCost(
  operationType: 'image_generation' | 'face_model_training',
  options?: { resolution?: Resolution; batchSize?: number }
): number {
  switch (operationType) {
    case 'image_generation':
      return calculateImageCreditCost(options?.resolution || '1K', options?.batchSize || 1);
    case 'face_model_training':
      return getFaceModelTrainingCost();
    default:
      throw new Error(`Unknown operation type: ${operationType}`);
  }
}

/**
 * Version string to help with tracking pricing changes
 */
export const PRICING_VERSION = '2.0.0'; 
