-- Insert style configs
INSERT INTO "public"."style_configs" ("id", "name", "tagline", "description", "preview_images", "available_genders", "available_backgrounds", "available_clothing", "available_clothing_colors", "created_at", "updated_at") 
VALUES 
('corporate', 'Corporate', 'Professional. Approachable. Trusted.', 'Professional and approachable, perfect for LinkedIn, team pages, and pitch decks — designed to make a confident first impression.', '["business-2.webp","business-1.webp","business-3.webp","business-1.webp","business-3.webp"]', ARRAY['male','female'], ARRAY['plain-light','plain-dark','plain-orange','plain-blue','plain-teal','studio','gradient','brick'], ARRAY['suit-jacket-shirt','shirt','polo','henley','jacket'], ARRAY['#000000','#FFFFFF','#2A9D47','#3B82F6','#FF7F39','#D22D2D','#FC84E2','#A28DF7','#6B7280','#4F46E5'], '2025-04-23 23:42:59.539907+00', '2025-04-23 23:42:59.539907+00'),
('editorial', 'Editorial', 'Story-Driven. Stylised. Striking.', 'A cinematic, magazine-worthy aesthetic. Expressive and fashion-forward — stand out with personality and mood.', '["outdoor-fashion-1.webp","outdoor-fashion-2.webp","outdoor-fashion-3.webp","outdoor-fashion-4.webp","outdoor-fashion-4.webp"]', ARRAY['male','female'], ARRAY['plain-light','plain-dark','plain-orange','plain-blue','plain-teal','studio','gradient','brick'], ARRAY['hoodie','shirt','polo','henley','jacket','fishermans-jumper'], ARRAY['#000000','#FFFFFF','#2A9D47','#3B82F6','#FF7F39','#D22D2D','#FC84E2','#A28DF7','#6B7280','#4F46E5'], '2025-04-23 23:42:59.539907+00', '2025-04-23 23:42:59.539907+00'),
('studio', 'Studio', 'Polished. Professional. Powerful.', 'Step into the spotlight with Studio style — clean, high-impact headshots perfect for portfolios, castings, and personal branding.', '["studio-1.webp","studio-2.webp","studio-3.webp","studio-1.webp","studio-2.webp"]', ARRAY['male','female'], ARRAY['plain-light','plain-dark','plain-orange','plain-blue','plain-teal','studio','gradient','brick'], ARRAY['hoodie','suit-jacket-shirt','shirt','polo','henley','jacket','fishermans-jumper'], ARRAY['#000000','#FFFFFF','#2A9D47','#3B82F6','#FF7F39','#D22D2D','#FC84E2','#A28DF7','#6B7280','#4F46E5'], '2025-04-23 23:42:59.539907+00', '2025-04-23 23:42:59.539907+00');

-- Insert style options
INSERT INTO "public"."style_options" ("category", "label", "description", "options", "created_at", "updated_at") 
VALUES 
('background', 'Background', 'Pick a background style. The examples give a general feel, actual results may differ slightly.', '[{"id": "plain-light", "label": "Studio Light", "imageUrl": "bg-plain-light.webp"}, {"id": "plain-dark", "label": "Studio Dark", "imageUrl": "bg-plain-dark.webp"}, {"id": "plain-orange", "label": "Studio Orange", "imageUrl": "bg-plain-orange.webp"}, {"id": "plain-blue", "label": "Studio Blue", "imageUrl": "bg-plain-blue.webp"}, {"id": "plain-teal", "label": "Studio Teal", "imageUrl": "bg-plain-teal.webp"}, {"id": "office", "label": "Office", "imageUrl": "bg-office.jpg"}, {"id": "outdoor", "label": "Outdoor", "imageUrl": "placeholder.jpg"}, {"id": "bookshelf", "label": "Bookshelf", "imageUrl": "bg-bookshelf.jpg"}, {"id": "cafe", "label": "Cafe", "imageUrl": "bg-cafe.jpg"}, {"id": "studio", "label": "Studio", "imageUrl": "placeholder.jpg"}, {"id": "gradient", "label": "Gradient", "imageUrl": "placeholder.jpg"}, {"id": "cityscape", "label": "Cityscape", "imageUrl": "placeholder.jpg"}, {"id": "abstract", "label": "Abstract", "imageUrl": "placeholder.jpg"}, {"id": "brick", "label": "Brick Wall", "imageUrl": "placeholder.jpg"}, {"id": "nature", "label": "Nature", "imageUrl": "placeholder.jpg"}, {"id": "tech", "label": "Tech Space", "imageUrl": "placeholder.jpg"}]', '2025-04-23 23:42:59.539907+00', '2025-04-23 23:42:59.539907+00'),
('clothing', 'Clothing Type', 'Choose a clothing style for your headshot. The samples are representative, but the final look may vary.', '[{"id": "hoodie", "label": "Hoodie", "imageUrl": "hoodie.webp"}, {"id": "suit-jacket-shirt", "label": "Suit Jacket/Shirt", "imageUrl": "blazer-shirt.webp"}, {"id": "shirt", "label": "Shirt", "imageUrl": "shirt.webp"}, {"id": "polo", "label": "Polo", "imageUrl": "polo.webp"}, {"id": "henley", "label": "Henley", "imageUrl": "henley.webp"}, {"id": "jacket", "label": "Jacket", "imageUrl": "jacket.webp"}, {"id": "fishermans-jumper", "label": "Fishermans Jumper", "imageUrl": "fishermans-jumper.webp"}]', '2025-04-23 23:42:59.539907+00', '2025-04-23 23:42:59.539907+00'),
('clothingColor', 'Clothing Color', 'Select a clothing colour you prefer. The shade shown is a guide, results may have subtle differences.', '[{"id": "#000000", "label": "Black"}, {"id": "#FFFFFF", "label": "White"}, {"id": "#2A9D47", "label": "Green"}, {"id": "#3B82F6", "label": "Blue"}, {"id": "#FF7F39", "label": "Orange"}, {"id": "#D22D2D", "label": "Red"}, {"id": "#FC84E2", "label": "Pink"}, {"id": "#A28DF7", "label": "Purple"}, {"id": "#6B7280", "label": "Gray"}, {"id": "#4F46E5", "label": "Indigo"}]', '2025-04-23 23:42:59.539907+00', '2025-04-23 23:42:59.539907+00'); 