#!/usr/bin/env node

/**
 * Script to sync pricing configuration from common package to Supabase functions
 * This eliminates duplication while avoiding Deno import issues
 */

import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

// Get current directory for ES modules
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Read the common pricing config
const commonPricingPath = join(__dirname, '../common/lib/pricing-config.ts');
const supabasePricingPath = join(__dirname, '../supabase/functions/_shared/pricing.ts');

console.log('🔄 Syncing pricing configuration...');

// Read the common config
const commonConfig = readFileSync(commonPricingPath, 'utf8');

// Extract the data we need - more robust regex patterns
const subscriptionTiersMatch = commonConfig.match(/export const SUBSCRIPTION_TIERS_CONFIG: SubscriptionTierConfig\[\] = (\[[\s\S]*?\]);/);
const creditPacksMatch = commonConfig.match(/export const CREDIT_PACKS_CONFIG: CreditPackConfig\[\] = (\[[\s\S]*?\]);/);

if (!subscriptionTiersMatch || !creditPacksMatch) {
  console.error('❌ Failed to extract pricing data from common config');
  console.error('Subscription tiers found:', !!subscriptionTiersMatch);
  console.error('Credit packs found:', !!creditPacksMatch);
  process.exit(1);
}

// Generate the new Supabase pricing file
const newSupabasePricing = `/**
 * SUPABASE EDGE FUNCTIONS PRICING CONSTANTS
 * 
 * ⚠️  AUTO-GENERATED - DO NOT EDIT MANUALLY!
 * This file is generated by scripts/sync-pricing.ts
 * To update pricing, edit common/lib/pricing-config.ts and run: npm run sync-pricing
 * 
 * Environment Variables (configurable in Supabase dashboard):
 * - CREDIT_COST_1K: Cost for 1K image generation (default: 1)
 * - CREDIT_COST_2K: Cost for 2K image generation (default: 2)
 * - CREDIT_COST_4K: Cost for 4K image generation (default: 3)
 * - CREDIT_COST_FACE_MODEL_TRAINING: Cost for Face Model training (default: 30)
 */

export type Resolution = '1K' | '2K' | '4K';

export interface CreditCosts {
  IMAGE_GENERATION: {
    [K in Resolution]: number;
  };
  FACE_MODEL_TRAINING: number;
}

export interface SubscriptionTier {
  id: string;
  name: string;
  displayName: string;
  description: string;
  monthlyPrice: number;
  yearlyPrice: number;
  credits: number;
  maxResolution: Resolution;
  faceModelTrainingIncluded: number;
  concurrentJobs: number;
  maxFaceModels: number;
  features: string[];
  popular?: boolean;
}

export interface CreditPack {
  id: string;
  name: string;
  credits: number;
  price: number;
  validityDays: number;
  costPerCredit: number;
  savings?: string;
}

/**
 * CONFIGURABLE CREDIT COSTS - reads from environment variables!
 * This is the main benefit - change pricing without code deployment
 */
export const CREDIT_COSTS: CreditCosts = {
  IMAGE_GENERATION: {
    '1K': parseInt(Deno.env.get('CREDIT_COST_1K') || '1'),
    '2K': parseInt(Deno.env.get('CREDIT_COST_2K') || '2'),
    '4K': parseInt(Deno.env.get('CREDIT_COST_4K') || '3')
  },
  FACE_MODEL_TRAINING: parseInt(Deno.env.get('CREDIT_COST_FACE_MODEL_TRAINING') || '30')
};

/**
 * Subscription tiers configuration
 * ⚠️  AUTO-GENERATED from common/lib/pricing-config.ts
 */
const SUBSCRIPTION_TIERS_CONFIG = ${subscriptionTiersMatch[1]};

// Convert config format to match our SubscriptionTier interface
export const SUBSCRIPTION_TIERS: SubscriptionTier[] = SUBSCRIPTION_TIERS_CONFIG.map(tier => ({
  ...tier,
  // Convert monthly yearly price to annual price for consistency
  yearlyPrice: tier.yearlyPrice * 12
}));

/**
 * Credit packs configuration
 * ⚠️  AUTO-GENERATED from common/lib/pricing-config.ts
 */
export const CREDIT_PACKS: CreditPack[] = ${creditPacksMatch[1]};

/**
 * Calculate credit cost for image generation
 */
export function calculateImageCreditCost(resolution: Resolution = '1K', batchSize: number = 1): number {
  return CREDIT_COSTS.IMAGE_GENERATION[resolution] * batchSize;
}

/**
 * Get credit cost for Face Model training
 */
export function getFaceModelTrainingCost(): number {
  return CREDIT_COSTS.FACE_MODEL_TRAINING;
}

/**
 * Calculate total credit cost for any operation
 */
export function calculateCreditCost(
  operationType: 'image_generation' | 'face_model_training',
  options?: { resolution?: Resolution; batchSize?: number }
): number {
  switch (operationType) {
    case 'image_generation':
      return calculateImageCreditCost(options?.resolution || '1K', options?.batchSize || 1);
    case 'face_model_training':
      return getFaceModelTrainingCost();
    default:
      throw new Error(\`Unknown operation type: \${operationType}\`);
  }
}

/**
 * Version string to help with tracking pricing changes
 */
export const PRICING_VERSION = '2.0.0'; 
`;

// Write the new file
writeFileSync(supabasePricingPath, newSupabasePricing);

console.log('✅ Pricing configuration synced successfully!');
console.log('📄 Updated:', supabasePricingPath);
console.log('');
console.log('To update pricing in the future:');
console.log('1. Edit common/lib/pricing-config.ts');
console.log('2. Run: npm run sync-pricing');
console.log('3. Deploy Supabase functions'); 