-- Add metadata column to characters table for storing physical analysis from Claude
-- This will store structured JSON data about the person's physical characteristics
-- analyzed automatically during the training process

ALTER TABLE characters 
ADD COLUMN metadata JSONB;

-- Add a comment explaining the purpose of this column
COMMENT ON COLUMN characters.metadata IS 'Stores structured JSON metadata about the character''s physical characteristics, automatically generated by Claude API during training. Contains fields like gender, age, hair, eyes, glasses, accessories, etc.';

-- Create an index on the metadata column for efficient JSON queries
CREATE INDEX idx_characters_metadata ON characters USING GIN (metadata);

-- Update the service role permissions to allow updates to the metadata column
-- This ensures the modal training app can update the metadata after analysis
GRANT SELECT, INSERT, UPDATE (metadata) ON characters TO service_role;