// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT EDIT MANUALLY
// Source: scripts/generate-types.ts
// Generated from: lib/config/styles.json and lib/config/options.json

// Re-generate by running: npm run generate-types

import { StylePhotographyStyle, StyleBackground, StyleOutfit } from './generated-types';

export const validStyleIds: StylePhotographyStyle[] = [
  "studio",
  "corporate",
  "editorial"
] as const;

export const validBackgrounds: StyleBackground[] = [
  "plain-light",
  "plain-dark",
  "plain-orange",
  "plain-blue",
  "plain-teal",
  "office",
  "outdoor",
  "bookshelf",
  "cafe",
  "studio",
  "gradient",
  "cityscape",
  "abstract",
  "brick",
  "nature",
  "tech"
] as const;

export const validOutfits: StyleOutfit[] = [
  "hoodie",
  "blazer-shirt",
  "shirt",
  "polo",
  "henley",
  "jacket",
  "fishermans-jumper"
] as const;

// Generated on: 2025-04-22T20:12:14.109Z
