// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT EDIT MANUALLY
// Source: scripts/generate-types.ts
// Generated from: lib/config/styles.json and lib/config/options.json

// Re-generate by running: npm run generate-types

import { StylePhotographyStyle, StyleBackground, StyleOutfit } from './generated-types';

export const validStyleIds: StylePhotographyStyle[] = [
  "studio",
  "corporate",
  "editorial",
  "editorial-2",
  "studio-2",
  "corporate-2"
] as const;

export const validBackgrounds: StyleBackground[] = [
  "plain",
  "office",
  "outdoor",
  "bookshelf",
  "cafe",
  "studio",
  "gradient",
  "cityscape",
  "abstract",
  "brick",
  "nature",
  "tech"
] as const;

export const validOutfits: StyleOutfit[] = [
  "professional",
  "business-casual",
  "casual",
  "creative",
  "tech",
  "startup",
  "formal"
] as const;

// Generated on: 2025-04-21T20:07:48.214Z
