// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT EDIT MANUALLY
// Source: scripts/generate-types.ts
// Generated from: lib/config/styles.json and lib/config/options.json

// Re-generate by running: npm run generate-types

export type StylePhotographyStyle = 
  | 'studio'
  | 'business-portrait'
  | 'outdoor-fashion'
  | 'outdoor-fashion-2'
  | 'studio-2'
  | 'business-portrait-2'

export type StyleBackground = 
  | 'plain'
  | 'office'
  | 'outdoor'
  | 'bookshelf'
  | 'cafe'
  | 'studio'
  | 'gradient'
  | 'cityscape'
  | 'abstract'
  | 'brick'
  | 'nature'
  | 'tech'

export type StyleOutfit = 
  | 'professional'
  | 'business-casual'
  | 'casual'
  | 'creative'
  | 'tech'
  | 'startup'
  | 'formal'

// Common types - manually maintained
export type StyleStatus = 'draft' | 'pending' | 'processing' | 'completed'

// Colors are strings (hex values, etc.)
export type StyleOutfitColor = string

export type StyleSettings = {
  photographyStyle: StylePhotographyStyle
  outfit: StyleOutfit
  background: StyleBackground
  outfitColor?: StyleOutfitColor
  customSettings?: Record<string, any>
}

// Generated on: 2025-04-18T21:49:51.321Z
