// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT EDIT MANUALLY
// Source: scripts/generate-types.ts
// Generated from: lib/config/styles.json and lib/config/options.json

// Re-generate by running: npm run generate-types

export type StylePhotographyStyle = 
  | 'studio'
  | 'corporate'
  | 'editorial'

export type StyleBackground = 
  | 'plain-light'
  | 'plain-dark'
  | 'plain-orange'
  | 'plain-blue'
  | 'plain-teal'
  | 'office'
  | 'outdoor'
  | 'bookshelf'
  | 'cafe'
  | 'studio'
  | 'gradient'
  | 'cityscape'
  | 'abstract'
  | 'brick'
  | 'nature'
  | 'tech'

export type StyleOutfit = 
  | 'hoodie'
  | 'blazer-shirt'
  | 'shirt'
  | 'polo'
  | 'henley'
  | 'jacket'
  | 'fishermans-jumper'

// Common types - manually maintained
export type StyleStatus = 'draft' | 'pending' | 'processing' | 'completed'

// Colors are strings (hex values, etc.)
export type StyleOutfitColor = string

// Gender type for user profiles and style settings
export type Gender = 'male' | 'female'

export type StyleSettings = {
  photographyStyle: StylePhotographyStyle
  outfit: StyleOutfit
  background: StyleBackground
  outfitColor?: StyleOutfitColor
  gender?: Gender
  customSettings?: Record<string, any>
}

// Generated on: 2025-04-22T20:12:14.108Z
